# Numpy exercises

HINT: use the Numpy documentations
* [NumPy User Guide](https://numpy.org/doc/1.22/user/index.html#user)
* [NumPy API](https://numpy.org/doc/1.22/reference/index.html#reference)

In [2]:

  import numpy as np

#### 1) Create a null vector of size 10 (★☆☆)

In [3]:
tenZeros = np.zeros(10)
tenZeros


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 2) Print the memory size in bytes of any array (★☆☆)

In [4]:
Z = np.zeros((10,10))

# Speicherplatz berechnen
memory_size = Z.size * Z.itemsize

print(f"Speichergröße: {memory_size} Bytes")



Speichergröße: 800 Bytes


#### 3) Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [5]:
Z = np.zeros(10)

Z[4]=1

Z


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 4) Create a vector with values ranging from 20 to 80 (★☆☆)

In [6]:
x = np.arange(20, 80, 10)
x

array([20, 30, 40, 50, 60, 70])

#### 5) Reverse a vector (first element becomes last) (★☆☆)

In [7]:
Z = np.arange(50)

Zflip = np.flip(Z,axis=0)
Zflip


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### 6) Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [8]:
Z = np.arange(9).reshape(3,3)
Z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 7) Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [9]:
array = np.array([1,2,0,0,4,0])

indicis = np.where(array == 0)

print(indicis)

(array([2, 3, 5]),)


#### 8) Create a 3x3 identity matrix (★☆☆)

In [10]:
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 9) Create a 3x3x3 array with random values (★☆☆)

In [11]:
random_array = np.random.rand(3, 3, 3)

print(random_array)

[[[0.32998854 0.11667129 0.55217514]
  [0.7998871  0.55447592 0.92898062]
  [0.45545685 0.97085179 0.41987952]]

 [[0.99937631 0.70040887 0.11200333]
  [0.70900045 0.4552628  0.04240616]
  [0.40636105 0.64927522 0.19752641]]

 [[0.54784553 0.20581768 0.90280998]
  [0.63600511 0.38728017 0.88877326]
  [0.04337646 0.03500927 0.55452954]]]


#### 10) Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
random = np.random.rand(10,10)

print(random)

print(np.max(random))
print(np.min(random))

[[0.73991445 0.51858681 0.53234011 0.74003468 0.02192604 0.36665001
  0.22571622 0.21161064 0.00902398 0.63114009]
 [0.46529559 0.59476821 0.93236093 0.18075529 0.89454059 0.00533489
  0.17886131 0.51347659 0.05221203 0.95879426]
 [0.82466448 0.80587665 0.04979533 0.83847164 0.94395276 0.13052937
  0.91997097 0.70212724 0.06502204 0.65059319]
 [0.42763802 0.04833879 0.53755513 0.68749007 0.1788572  0.14962925
  0.6452045  0.80130413 0.49647258 0.67735482]
 [0.75686018 0.62394729 0.8425775  0.416882   0.78651902 0.40074249
  0.14868884 0.55401552 0.60545523 0.45351049]
 [0.15725257 0.85305516 0.07376081 0.59791672 0.77996506 0.64515276
  0.05195844 0.70241621 0.6492764  0.85853161]
 [0.74480985 0.46971623 0.30939979 0.02412912 0.70881114 0.14850875
  0.76076921 0.81588711 0.09209926 0.63572527]
 [0.62742317 0.73381046 0.67782738 0.89381064 0.24089547 0.23486283
  0.95994457 0.44961578 0.63662191 0.20990878]
 [0.58054013 0.03056657 0.9638936  0.43202105 0.17481498 0.70794234
  0.71785881

#### 11) Create a random vector of size 30 and find the mean, variance values (★☆☆)

In [17]:
another = np.random.rand(30)

mean = np.mean(another)
variance = np.var(another)

print(mean)
print(variance)

0.565575907081844
0.09674081337516341


#### 12) Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [31]:
Z = np.ones((10,10))
Z[1:-1, 1:-1] = 0  # Innenbereich auf 0 setzen
print(Z)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 13) How to add a border (filled with 0's) around an existing array? (★☆☆)

In [32]:
Z = np.ones((5,5))

# Mit 0er-Rand erweitern
Z_padded = np.pad(Z, pad_width=1, mode='constant', constant_values=0)

print(Z_padded)


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 14) Predict (before executing) the results of the following expressions? (★☆☆)

In [33]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 15) Create a 6×6 matrix with values 1,2,3,4,5 just below the diagonal (★☆☆)

In [34]:
Z = np.diag(np.arange(1, 6), k=-1)

print(Z)

[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]]


#### 16) Create a 8x8 matrix and fill it with a checkerboard (0,1) pattern (★☆☆)

In [36]:
Z = np.zeros((8,8),dtype=int)


Z[1::2, ::2] = 1
Z[::2, 1::2] = 1

print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 17) Consider a (5,6,7) shape array, what is the index (x, y, z) of the 50th element?

In [37]:
shape = (5,6,7)
linear_index = 49

index = np.unravel_index(linear_index, shape)

print(index)

(np.int64(1), np.int64(1), np.int64(0))


#### 18) Multiply a 4x2 matrix by a 2x3 matrix (real matrix product) (★☆☆)

In [40]:
A = np.random.random((4,2))
B =  np.random.random((2,3))

C = np.dot(A, B)

print(C)

[[0.04367848 0.37300878 0.51858479]
 [0.31070556 0.62589638 1.18450516]
 [0.16578124 0.19176593 0.456371  ]
 [0.19452239 0.32620382 0.66048704]]


#### 19) Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [42]:
# Author: Evgeni Burovski

Z = np.arange(11)


Z[(Z >= 3) & (Z <= 8)] *= -1  # Negiere Werte zwischen 3 und 8

print(Z)


[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


#### 20. How to find common values between two arrays? (★☆☆)

In [43]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)

common_values = np.intersect1d(Z1, Z2)

print(common_values)

[0 4 5 8]


#### 21) How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3


#### 22) Extract the integer part of a random array (★★☆)

In [ ]:
Z = np.random.uniform(0,10,10)



#### 23) Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
Z = np.zeros((5,5))


#### 24) Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 25) Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 26) Create a random vector of size 10 and sort it (★★☆)

#### 27) Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)



#### 28) Make an array immutable (read-only) (★★☆)

In [ ]:
Z = np.zeros(10)


#### 29) Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
Z = np.random.random(10)


#### 30) How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
Z = np.arange(10, dtype=np.float32)


#### 31) randomly place 3 elements in a 2D array? (★★☆)

In [ ]:
n = 10
p = 3
Z = np.zeros((n,n))


#### 32) Subtract the mean of each row of a matrix (★★☆)

In [ ]:
X = np.random.rand(5, 10)


#### 33) sort an array by the 1st column? (★★☆)

In [ ]:
Z = np.random.randint(0,10,(3,3))
Z

array([[2, 8, 3],
       [3, 0, 4],
       [3, 3, 7]])

#### 34) Find the nearest value from a given value z in an array Z(★★☆)

In [ ]:
Z = np.random.uniform(0,1,10)
z = 0.5


#### 35) Considering two arrays with shape (1,3) and (3,1): to compute their sum using an iterator (★★☆)

In [ ]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)


#### 36) find the most frequent value in an array

In [ ]:
Z = np.random.randint(0,10,50)


#### 37) Given a two dimensional array, extract unique rows (★★★)

In [ ]:
Z = np.random.randint(0,2,(6,3))
