# Numpy exercises

HINT: use the Numpy documentations
* [NumPy User Guide](https://numpy.org/doc/1.22/user/index.html#user)
* [NumPy API](https://numpy.org/doc/1.22/reference/index.html#reference)

In [2]:

  import numpy as np

#### 1) Create a null vector of size 10 (★☆☆)

In [12]:
tenZeros = np.zeros(10)
tenZeros


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 2) Print the memory size in bytes of any array (★☆☆)

In [10]:
Z = np.zeros((10,10))

# Speicherplatz berechnen
memory_size = Z.size * Z.itemsize

print(f"Speichergröße: {memory_size} Bytes")



Speichergröße: 800 Bytes


#### 3) Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [13]:
Z = np.zeros(10)

Z[4]=1

Z


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 4) Create a vector with values ranging from 20 to 80 (★☆☆)

In [14]:
x = np.arange(20, 80, 10)
x

array([20, 30, 40, 50, 60, 70])

#### 5) Reverse a vector (first element becomes last) (★☆☆)

In [16]:
Z = np.arange(50)

Zflip = np.flip(Z,axis=0)
Zflip


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### 6) Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [22]:
Z = np.arange(9).reshape(3,3)
Z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 7) Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [26]:
array = np.array([1,2,0,0,4,0])

indicis = np.where(array == 0)

print(indicis)

(array([2, 3, 5]),)


#### 8) Create a 3x3 identity matrix (★☆☆)

#### 9) Create a 3x3x3 array with random values (★☆☆)

#### 10) Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

#### 11) Create a random vector of size 30 and find the mean, variance values (★☆☆)

#### 12) Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
Z = np.ones((10,10))


#### 13) How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
Z = np.ones((5,5))


#### 14) Predict (before executing) the results of the following expressions? (★☆☆)

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 15) Create a 6×6 matrix with values 1,2,3,4,5 just below the diagonal (★☆☆)

#### 16) Create a 8x8 matrix and fill it with a checkerboard (0,1) pattern (★☆☆)

In [ ]:
Z = np.zeros((8,8),dtype=int)


#### 17) Consider a (5,6,7) shape array, what is the index (x, y, z) of the 50th element?

#### 18) Multiply a 4x2 matrix by a 2x3 matrix (real matrix product) (★☆☆)

#### 19) Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
# Author: Evgeni Burovski

Z = np.arange(11)


#### 20. How to find common values between two arrays? (★☆☆)

In [ ]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)


#### 21) How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3


#### 22) Extract the integer part of a random array (★★☆)

In [ ]:
Z = np.random.uniform(0,10,10)



#### 23) Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
Z = np.zeros((5,5))


#### 24) Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 25) Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 26) Create a random vector of size 10 and sort it (★★☆)

#### 27) Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)



#### 28) Make an array immutable (read-only) (★★☆)

In [ ]:
Z = np.zeros(10)


#### 29) Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
Z = np.random.random(10)


#### 30) How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
Z = np.arange(10, dtype=np.float32)


#### 31) randomly place 3 elements in a 2D array? (★★☆)

In [ ]:
n = 10
p = 3
Z = np.zeros((n,n))


#### 32) Subtract the mean of each row of a matrix (★★☆)

In [ ]:
X = np.random.rand(5, 10)


#### 33) sort an array by the 1st column? (★★☆)

In [ ]:
Z = np.random.randint(0,10,(3,3))
Z

array([[2, 8, 3],
       [3, 0, 4],
       [3, 3, 7]])

#### 34) Find the nearest value from a given value z in an array Z(★★☆)

In [ ]:
Z = np.random.uniform(0,1,10)
z = 0.5


#### 35) Considering two arrays with shape (1,3) and (3,1): to compute their sum using an iterator (★★☆)

In [ ]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)


#### 36) find the most frequent value in an array

In [ ]:
Z = np.random.randint(0,10,50)


#### 37) Given a two dimensional array, extract unique rows (★★★)

In [ ]:
Z = np.random.randint(0,2,(6,3))
