# Recalling Numpy Array Slicing and Indexing

In [3]:
import numpy as np

In [4]:
#create array
x = np.asarray(range(1,26), np.int8).reshape(5,5)

In [5]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]], dtype=int8)

## Slice first 3 elements

<img src="https://github.com/Ambos14/DataEng25/blob/main/week_1/IMG/np01.png?raw=1">

In [7]:
x[0,0:3]


array([1, 2, 3], dtype=int8)

##  Slice first 8 elements

<img src="https://github.com/Ambos14/DataEng25/blob/main/week_1/IMG/np02.png?raw=1">

In [12]:
first = x[0,:]
second = x[1,0:3]
both = np.concatenate((first, second), axis = 0)

both

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int8)

## Skip every other element

<img src="https://github.com/Ambos14/DataEng25/blob/main/week_1/IMG/np03.png?raw=1">

In [19]:
x[0,::2]

array([1, 3, 5], dtype=int8)

## Slice first column

<img src="https://github.com/Ambos14/DataEng25/blob/main/week_1/IMG/np04.png?raw=1">

In [21]:
x[0:4,0]

array([ 1,  6, 11, 16], dtype=int8)

## Slice a diagonal

<img src="https://github.com/Ambos14/DataEng25/blob/main/week_1/IMG/np05.png?raw=1">

In [25]:
result = np.diagonal(x,offset=0)
result

array([ 1,  7, 13, 19, 25], dtype=int8)

## Repeat the first element

<img src="https://github.com/Ambos14/DataEng25/blob/main/week_1/IMG/np06.png?raw=1">

In [30]:
 more2 = np.repeat(x[0,0],5)

 more2


array([1, 1, 1, 1, 1], dtype=int8)

## Simple 2D slicing

<img src="https://github.com/Ambos14/DataEng25/blob/main/week_1/IMG/np07.png?raw=1">

In [32]:
x[0:3,0:4]

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14]], dtype=int8)

## Slice a zigzag

<img src="https://github.com/Ambos14/DataEng25/blob/main/week_1/IMG/np08.png?raw=1">

In [45]:
theCenterNotReady = np.diagonal(x,offset=0)
theCenter = theCenterNotReady[:-1]
theCenter
anoterColumn = np.diagonal(x,offset=1)
anoterColumn
result = np.column_stack((theCenter,anoterColumn))
result

array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20]], dtype=int8)

## Sparse slicing

<img src="https://github.com/Ambos14/DataEng25/blob/main/week_1/IMG/np09.png?raw=1">

In [46]:
x[::2,::2]

array([[ 1,  3,  5],
       [11, 13, 15],
       [21, 23, 25]], dtype=int8)

## Transpose a 2D array

<img src="https://github.com/Ambos14/DataEng25/blob/main/week_1/IMG/np10.png?raw=1">

In [51]:
firstSlice = x[0:3,0:3]
firstSlice = np.rot90(firstSlice)
firstSlice = np.flip(firstSlice,axis=0)
firstSlice

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13]], dtype=int8)

## Repeat the first column 4 times


<img src="https://github.com/Ambos14/DataEng25/blob/main/week_1/IMG/np11.png?raw=1">

In [84]:
this = x[:,0]
column = this.reshape(-1,1)
columnMore = np.column_stack((column,column, column,column))
columnMore

array([[ 1,  1,  1,  1],
       [ 6,  6,  6,  6],
       [11, 11, 11, 11],
       [16, 16, 16, 16],
       [21, 21, 21, 21]], dtype=int8)

## Reshape 1D array to 2D array

<img src="https://github.com/Ambos14/DataEng25/blob/main/week_1/IMG/np12.png?raw=1">

In [ ]:
x = np.asarray(range(1,13), np.int64)
print(x)


[ 1  2  3  4  5  6  7  8  9 10 11 12]


## Collapse an axis from a 3D array

<img src="https://github.com/Ambos14/DataEng25/blob/main/week_1/IMG/np13.png?raw=1">

In [ ]:
x = np.asarray(range(1,13), np.int8).reshape(3,2,2)
print(x)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
